# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 2

python:
  version: 3.11  # https://github.com/pylint-dev/astroid/pull/2165/files
  install:
  - requirements: doc/requirements.txt
  system_packages: false
