# SPDX-FileCopyrightText: : 2021-2022 The PyPSA-Earth Authors
#
# SPDX-License-Identifier: CC0-1.0

### CHANGES TO CONFIG.TUTORIAL.YAML ###
retrieve_databundle: # required to be "false" for nice CI test output
  show_progress: false

countries:
- NG

run:
  name: NG
  shared_cutouts: true # set to true to share the default cutout(s) across runs

scenario:
  clusters: [5]

enable:
  retrieve_databundle: false
