# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: pypsa-earth
channels:
- bioconda
- gurobi
- conda-forge
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- affine=2.4.0
- alsa-lib=1.2.9
- amply=0.1.6
- anyio=3.7.1
- appdirs=1.4.4
- argon2-cffi=23.1.0
- argon2-cffi-bindings=21.2.0
- arrow=1.2.3
- asttokens=2.2.1
- async-lru=2.0.4
- atk-1.0=2.38.0
- atlite=0.2.11
- attr=2.5.1
- attrs=23.1.0
- aws-c-auth=0.7.3
- aws-c-cal=0.6.2
- aws-c-common=0.9.0
- aws-c-compression=0.2.17
- aws-c-event-stream=0.3.2
- aws-c-http=0.7.12
- aws-c-io=0.13.32
- aws-c-mqtt=0.9.5
- aws-c-s3=0.3.14
- aws-c-sdkutils=0.1.12
- aws-checksums=0.1.17
- aws-crt-cpp=0.23.0
- aws-sdk-cpp=1.10.57
- babel=2.12.1
- backcall=0.2.0
- backports=1.0
- backports.functools_lru_cache=1.6.5
- beautifulsoup4=4.12.2
- bleach=6.0.0
- blosc=1.21.4
- bokeh=3.2.2
- boltons=23.0.0
- boost-cpp=1.78.0
- bottleneck=1.3.7
- branca=0.6.0
- brotli=1.0.9
- brotli-bin=1.0.9
- brotli-python=1.0.9
- bzip2=1.0.8
- c-ares=1.19.1
- c-blosc2=2.10.2
- ca-certificates=2023.7.22
- cached-property=1.5.2
- cached_property=1.5.2
- cairo=1.16.0
- cartopy=0.22.0
- cdsapi=0.6.1
- certifi=2023.7.22
- cffi=1.15.1
- cfgv=3.3.1
- cfitsio=4.3.0
- cftime=1.6.2
- charset-normalizer=3.2.0
- click=8.1.7
- click-plugins=1.1.1
- cligj=0.7.2
- cloudpickle=2.2.1
- coin-or-cbc=2.10.10
- coin-or-cgl=0.60.7
- coin-or-clp=1.17.8
- coin-or-osi=0.108.8
- coin-or-utils=2.11.9
- coincbc=2.10.10
- colorama=0.4.6
- colorcet=3.0.1
- comm=0.1.4
- conda=23.7.3
- conda-package-handling=2.2.0
- conda-package-streaming=0.9.0
- configargparse=1.7
- connection_pool=0.0.3
- contextily=1.3.0
- contourpy=1.1.0
- country_converter=1.0.0
- cryptography=41.0.3
- cycler=0.11.0
- cytoolz=0.12.2
- dask=2023.8.1
- dask-core=2023.8.1
- datashader=0.15.2
- datashape=0.5.4
- datrie=0.8.2
- dbus=1.13.6
- debugpy=1.6.8
- decorator=5.1.1
- defusedxml=0.7.1
- deprecation=2.1.0
- descartes=1.1.0
- distlib=0.3.7
- distributed=2023.8.1
- docutils=0.20.1
- dpath=2.1.6
- earth-osm=0.1.0
- entrypoints=0.4
- entsoe-py=0.5.10
- et_xmlfile=1.1.0
- exceptiongroup=1.1.3
- executing=1.2.0
- expat=2.5.0
- filelock=3.12.2
- fiona=1.9.4
- fmt=9.1.0
- folium=0.14.0
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.42.1
- fqdn=1.5.1
- freetype=2.12.1
- freexl=1.0.6
- fribidi=1.0.10
- fsspec=2023.6.0
- future=0.18.3
- gdal=3.7.1
- gdk-pixbuf=2.42.10
- geographiclib=1.52
- geojson-rewind=1.0.2
- geopandas=0.13.2
- geopandas-base=0.13.2
- geopy=2.3.0
- geos=3.12.0
- geotiff=1.7.1
- geoviews=1.10.1
- geoviews-core=1.10.1
- gettext=0.21.1
- gflags=2.2.2
- giflib=5.2.1
- gitdb=4.0.10
- gitpython=3.1.32
- glib=2.76.4
- glib-tools=2.76.4
- glog=0.6.0
- glpk=5.0
- gmp=6.2.1
- graphite2=1.3.13
- graphviz=8.1.0
- gst-plugins-base=1.22.5
- gstreamer=1.22.5
- gtk2=2.24.33
- gts=0.7.6
- gurobi=10.0.2
- harfbuzz=7.3.0
- hdf4=4.2.15
- hdf5=1.14.1
- holoviews=1.17.1
- humanfriendly=10.0
- hvplot=0.8.4
- icu=72.1
- identify=2.5.27
- idna=3.4
- importlib-metadata=6.8.0
- importlib_metadata=6.8.0
- importlib_resources=6.0.1
- iniconfig=2.0.0
- ipopt=3.13.2
- ipykernel=6.25.1
- ipython=8.14.0
- isoduration=20.11.0
- jedi=0.19.0
- jinja2=3.1.2
- joblib=1.3.2
- json-c=0.17
- json5=0.9.14
- jsonpatch=1.32
- jsonpointer=2.0
- jsonschema=4.19.0
- jsonschema-specifications=2023.7.1
- jsonschema-with-format-nongpl=4.19.0
- jupyter-lsp=2.2.0
- jupyter_client=8.3.0
- jupyter_core=5.3.1
- jupyter_events=0.7.0
- jupyter_server=2.7.1
- jupyter_server_terminals=0.4.4
- jupyterlab=4.0.5
- jupyterlab_pygments=0.2.2
- jupyterlab_server=2.24.0
- kealib=1.5.1
- keyutils=1.6.1
- kiwisolver=1.4.5
- krb5=1.21.2
- lame=3.100
- lcms2=2.15
- ld_impl_linux-64=2.40
- lerc=4.0.0
- libabseil=20230125.3
- libaec=1.0.6
- libarchive=3.6.2
- libarrow=13.0.0
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcap=2.69
- libcblas=3.9.0
- libclang=15.0.7
- libclang13=15.0.7
- libcrc32c=1.1.2
- libcups=2.3.3
- libcurl=8.2.1
- libdeflate=1.18
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.12
- libexpat=2.5.0
- libffi=3.4.2
- libflac=1.4.3
- libgcc-ng=13.1.0
- libgcrypt=1.10.1
- libgd=2.3.3
- libgdal=3.7.1
- libgfortran-ng=13.1.0
- libgfortran5=13.1.0
- libglib=2.76.4
- libgomp=13.1.0
- libgoogle-cloud=2.12.0
- libgpg-error=1.47
- libgrpc=1.56.2
- libiconv=1.17
- libjpeg-turbo=2.1.5.1
- libkml=1.3.0
- liblapack=3.9.0
- liblapacke=3.9.0
- libllvm14=14.0.6
- libllvm15=15.0.7
- libmamba=1.5.0
- libmambapy=1.5.0
- libnetcdf=4.9.2
- libnghttp2=1.52.0
- libnsl=2.0.0
- libnuma=2.0.16
- libogg=1.3.4
- libopenblas=0.3.23
- libopus=1.3.1
- libpng=1.6.39
- libpq=15.4
- libprotobuf=4.23.3
- librsvg=2.56.3
- librttopo=1.1.0
- libsndfile=1.2.2
- libsodium=1.0.18
- libsolv=0.7.24
- libspatialindex=1.9.3
- libspatialite=5.0.1
- libsqlite=3.43.0
- libssh2=1.11.0
- libstdcxx-ng=13.1.0
- libsystemd0=254
- libthrift=0.18.1
- libtiff=4.5.1
- libtool=2.4.7
- libutf8proc=2.8.0
- libuuid=2.38.1
- libvorbis=1.3.7
- libwebp=1.3.1
- libwebp-base=1.3.1
- libxcb=1.15
- libxkbcommon=1.5.0
- libxml2=2.11.5
- libxslt=1.1.37
- libzip=1.10.1
- libzlib=1.2.13
- linkify-it-py=2.0.0
- linopy=0.2.5
- llvmlite=0.40.1
- locket=1.0.0
- lxml=4.9.3
- lz4=4.3.2
- lz4-c=1.9.4
- lzo=2.10
- mamba=1.5.0
- mapclassify=2.5.0
- markdown=3.4.4
- markdown-it-py=3.0.0
- markupsafe=2.1.3
- matplotlib=3.5.2
- matplotlib-base=3.5.2
- matplotlib-inline=0.1.6
- mdit-py-plugins=0.4.0
- mdurl=0.1.0
- memory_profiler=0.61.0
- mercantile=1.2.1
- metis=5.1.1
- mistune=3.0.1
- mpg123=1.31.3
- msgpack-python=1.0.5
- multipledispatch=0.6.0
- munch=4.0.0
- munkres=1.1.4
- mysql-common=8.0.33
- mysql-libs=8.0.33
- nbclient=0.8.0
- nbconvert-core=7.7.4
- nbformat=5.9.2
- ncurses=6.4
- nest-asyncio=1.5.6
- netcdf4=1.6.4
- networkx=3.1
- nodeenv=1.8.0
- nomkl=1.0
- notebook-shim=0.2.3
- nspr=4.35
- nss=3.92
- numba=0.57.1
- numexpr=2.8.4
- numpy=1.24.4
- openjpeg=2.5.0
- openpyxl=3.1.2
- openssl=3.1.2
- orc=1.9.0
- overrides=7.4.0
- packaging=23.1
- pandas=2.0.3
- pandocfilters=1.5.0
- panel=1.2.1
- pango=1.50.14
- param=1.13.0
- parso=0.8.3
- partd=1.4.0
- patsy=0.5.3
- pcre2=10.40
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=10.0.0
- pip=23.2.1
- pixman=0.40.0
- pkgutil-resolve-name=1.3.10
- plac=1.3.5
- platformdirs=3.10.0
- pluggy=1.2.0
- ply=3.11
- pooch=1.7.0
- poppler=23.08.0
- poppler-data=0.4.12
- postgresql=15.4
- powerplantmatching=0.5.7
- pre-commit=3.3.3
- progressbar2=4.2.0
- proj=9.2.1
- prometheus_client=0.17.1
- prompt-toolkit=3.0.39
- prompt_toolkit=3.0.39
- protobuf=4.23.3
- psutil=5.9.5
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pulp=2.7.0
- pulseaudio-client=16.1
- pure_eval=0.2.2
- py-cpuinfo=9.0.0
- pyarrow=13.0.0
- pybind11-abi=4
- pycosat=0.6.4
- pycountry=22.3.5
- pycparser=2.21
- pyct=0.4.6
- pyct-core=0.4.6
- pydoe2=1.3.0
- pygments=2.16.1
- pyogrio=0.6.0
- pyomo=6.6.2
- pyopenssl=23.2.0
- pyparsing=3.1.1
- pyproj=3.6.0
- pypsa=0.24.0
- pyqt=5.15.9
- pyqt5-sip=12.12.2
- pyshp=2.3.1
- pysocks=1.7.1
- pytables=3.8.0
- pytest=7.4.0
- python=3.10.12
- python-dateutil=2.8.2
- python-fastjsonschema=2.18.0
- python-json-logger=2.0.7
- python-tzdata=2023.3
- python-utils=3.7.0
- python_abi=3.10
- pytz=2023.3
- pyviz_comms=3.0.0
- pyyaml=6.0.1
- pyzmq=25.1.1
- qt-main=5.15.8
- rasterio=1.3.8
- rdma-core=28.9
- re2=2023.03.02
- readline=8.2
- referencing=0.30.2
- reproc=14.2.4
- reproc-cpp=14.2.4
- requests=2.31.0
- reretry=0.11.8
- reverse-geocode=1.4.1
- rfc3339-validator=0.1.4
- rfc3986-validator=0.1.1
- rioxarray=0.15.0
- rpds-py=0.9.2
- rtree=1.0.1
- ruamel.yaml=0.17.26
- ruamel.yaml.clib=0.2.7
- s2n=1.3.49
- scikit-learn=1.3.0
- scipy=1.11.2
- seaborn=0.12.2
- seaborn-base=0.12.2
- send2trash=1.8.2
- setuptools=68.1.2
- shapely=2.0.1
- sip=6.7.11
- six=1.16.0
- smart_open=6.3.0
- smmap=3.0.5
- snakemake-minimal=7.32.3
- snappy=1.1.10
- sniffio=1.3.0
- snuggs=1.4.7
- sortedcontainers=2.4.0
- soupsieve=2.3.2.post1
- sqlite=3.43.0
- stack_data=0.6.2
- statsmodels=0.14.0
- stopit=1.1.2
- tabulate=0.9.0
- tblib=1.7.0
- terminado=0.17.1
- threadpoolctl=3.2.0
- throttler=1.2.2
- tiledb=2.16.3
- tinycss2=1.2.1
- tk=8.6.12
- toml=0.10.2
- tomli=2.0.1
- toolz=0.12.0
- toposort=1.10
- tornado=6.3.3
- tqdm=4.66.1
- traitlets=5.9.0
- typing-extensions=4.7.1
- typing_extensions=4.7.1
- typing_utils=0.1.0
- tzcode=2023c
- tzdata=2023c
- uc-micro-py=1.0.1
- ucx=1.14.1
- ukkonen=1.0.1
- unicodedata2=15.0.0
- unidecode=1.3.6
- uri-template=1.3.0
- urllib3=2.0.4
- validators=0.21.2
- virtualenv=20.24.3
- wcwidth=0.2.6
- webcolors=1.13
- webencodings=0.5.1
- websocket-client=1.6.2
- wheel=0.41.2
- wrapt=1.15.0
- xarray=2023.8.0
- xcb-util=0.4.0
- xcb-util-image=0.4.0
- xcb-util-keysyms=0.4.0
- xcb-util-renderutil=0.3.9
- xcb-util-wm=0.4.1
- xerces-c=3.2.4
- xkeyboard-config=2.39
- xlrd=2.0.1
- xorg-kbproto=1.0.7
- xorg-libice=1.1.1
- xorg-libsm=1.2.4
- xorg-libx11=1.8.6
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.11
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xf86vidmodeproto=2.3.1
- xorg-xproto=7.0.31
- xyzservices=2023.7.0
- xz=5.2.6
- yaml=0.2.5
- yaml-cpp=0.7.0
- yte=1.5.1
- zeromq=4.3.4
- zict=3.0.0
- zipp=3.16.2
- zlib=1.2.13
- zlib-ng=2.0.7
- zstandard=0.19.0
- zstd=1.5.2
- pip:
  - chaospy==4.3.13
  - countrycode==0.3.0
  - googledrivedownloader==0.4
  - highspy==1.5.3
  - numpoly==1.2.11
  - polars==0.18.15
  - tsam==2.3.1
  - vresutils==0.3.2.dev11+g150c1be
