# SPDX-FileCopyrightText: : 2021-2022 The PyPSA-Earth Authors
#
# SPDX-License-Identifier: CC0-1.0

# File describing the data bundle configurations that can be downloaded
# by using the retrieve_databundle fule

# Each bundle shall have the following structure:

# .. code:: yaml

#   bundle_name:  # name of the bundle
#     countries: [country code, region code or country list]  # list of countries represented in the databundle
#     [tutorial: true/false]  # (optional, default false) whether the bundle is a tutorial or not
#     category: common/resources/data/cutouts  # category of data contained in the bundle:
#     destination: "."  # folder where to unzip the files with respect to the repository root (\"\" or \".\")
#     urls:  # list of urls by source, e.g. zenodo or google
#       zenodo: {zenodo url}  # key to download data from zenodo
#       gdrive: {google url}  # key to download data from google drive
#       protectedplanet: {url}  # key to download data from protected planet
#       direct: {url}  # key to download data directly from a url; if unzip option is enabled data are unzipped
#       post:  # key to download data using an url post request; if unzip option is enabled data are unzipped
#         url: {url}
#         [post arguments]
#     [unzip: true/false]  # (optional, default false) used in direct download technique to automatically unzip files
#     output: [...] # list of outputs of the bundle used in snakemake
#     [disable_by_opt:]  # option to disable outputs from the bundle; it contains a dictionary of options, each one with
#                        # each one with its output. When "all" is specified, the entire bundle is not executed
#       [{option}: [outputs]/all]  # list of options and the outputs to remove, or "all" corresponding to ignore everything

databundles:
  # tutorial bundle specific for Nigeria and Benin only
  bundle_tutorial_NGBJ:
    countries: [NG, BJ]
    tutorial: true
    category: data
    destination: "data"
    urls:
      # zenodo: https://sandbox.zenodo.org/record/1016522/files/tutorial_data.zip?download=1
      gdrive: https://drive.google.com/file/d/1yg1D5o7FN19ypICQKOuKgKbcGqrOmbia/view?usp=share_link
    output:
    - data/gebco/GEBCO_2021_TID.nc
    - data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif

  # tutorial bundle specific for Botswana only
  bundle_tutorial_BW:
    countries: [BW]
    tutorial: true
    category: data
    destination: "data"
    urls:
      gdrive: https://drive.google.com/file/d/1yJ8JYGFVtMPpsEBeXzDR5Ixa9n8gGu5n/view?usp=share_link
    output:
    - data/gebco/GEBCO_2021_TID.nc
    - data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif

  # tutorial bundle specific for Morocco only
  bundle_tutorial_MA:
    countries: [MA]
    tutorial: true
    category: data
    destination: "data"
    urls:
      gdrive: https://drive.google.com/file/d/1Qjf0xVBuOSTKTPRD_NANruDDG94CF-Ju/view?usp=share_link
    output:
    - data/gebco/GEBCO_2021_TID.nc
    - data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif

  # tutorial bundle specific for Nigeria and Benin only
  bundle_cutouts_tutorial_NGBJ:
    countries: [NG, BJ]
    tutorial: true
    category: cutouts
    destination: "cutouts"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1016015/files/tutorial_cutouts.zip?download=1
      gdrive: https://drive.google.com/file/d/1No_BNKRO4UODdR5rVtwkfZjfVGUQKJ_K/view?usp=share_link
    output: [cutouts/africa-2013-era5-tutorial.nc]
    disable_by_opt:
      build_cutout: [all]

  # tutorial bundle specific for Botswana only
  bundle_cutouts_tutorial_BW:
    countries: [BW]
    tutorial: true
    category: cutouts
    destination: "cutouts"
    urls:
      gdrive: https://drive.google.com/file/d/19-vq48OKAeJ0C_1S8kx2HVQkCMGKzuTF/view?usp=share_link
    output: [cutouts/africa-2013-era5-tutorial.nc]
    disable_by_opt:
      build_cutout: [all]

  # tutorial bundle specific for Morocco only
  bundle_cutouts_tutorial_ma:
    countries: [MA]
    tutorial: true
    category: cutouts
    destination: "cutouts"
    urls:
      gdrive: https://drive.google.com/file/d/14mgef15MSwOTUxDtXcnPBJbC_M7zxalQ/view?usp=share_link
    output: [cutouts/africa-2013-era5-tutorial.nc]
    disable_by_opt:
      build_cutout: [all]

#tutorial bundle for all African countries
  bundle_tutorial_data_common:
    countries: [Africa]
    tutorial: true
    category: common
    destination: "data"
    urls:
      gdrive: https://drive.google.com/file/d/1yWxR7noWXZP74iRLqQGCatXssRGcuEc2/view?usp=share_link
    output:
    - data/costs.csv
    - data/hydro_capacities.csv
    - data/custom_powerplants.csv
    - data/eez/eez_v11.gpkg
    - data/ssp2-2.6/2030/era5_2013/Africa.nc
    - data/hydrobasins/hybas_world_lev04_v1c.shp
    - data/hydrobasins/hybas_world_lev05_v1c.shp

  # resources bundle containing the resources folder for africa only
  bundle_natura_earth:
    countries: [Earth]
    category: natura
    destination: "data"
    urls:
      # zenodo: https://sandbox.zenodo.org/record/1016878/files/resources_africa.zip?download=1
      gdrive: https://drive.google.com/file/d/1WmAAwY0TAcHg8YZyAGof0bPewFacm7my/view?usp=share_link
    output:
    - data/natura.tiff

  # data bundle of the data folder for the african continent
  bundle_landcover_africa:
    countries: [Africa]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1016042/files/landcover_africa.zip?download=1
      gdrive: https://drive.google.com/file/d/1l6Xgr3PXyvgqWaXUbto9zvvMS_OgSjvG/view?usp=sharing
    output: [data/landcover/*]

  # data bundle of the data folder for the african continent
  bundle_landcover_asiapacific:
    countries: [Asia, Oceania]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1016042/files/landcover_asiapacific.zip?download=1
      gdrive: https://drive.google.com/file/d/1HZGpxZdTB2Ai_VN_8SPivCdgt3oz0wkX/view?usp=sharing
    output: [data/landcover/*]

  # data bundle of the data folder for the african continent
  bundle_landcover_latinamerica_caribbean:  # excludes north america
    countries: [SouthAmerica, NorthAmerica]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1016042/files/landcover_latinamerica_caribbean.zip?download=1
      gdrive: https://drive.google.com/file/d/1lmBFPTHyzVmSx9qgrGh8D6uHiSyGaH_F/view?usp=sharing
    output: [data/landcover/*]

  # data bundle of the data folder for the african continent
  bundle_landcover_westasia:
    countries: [WAS]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1016042/files/landcover_westasia.zip?download=1
      gdrive: https://drive.google.com/file/d/1s9JRWJaeet4syInGap6FyqDBJIR80UHr/view?usp=sharing
    output: [data/landcover/*]

  # data bundle of the data folder for europe
  bundle_landcover_europe:
    countries: [Europe]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1018640/files/landcover_europe.zip?download=1
      gdrive: https://drive.google.com/file/d/1zQuKnZFp6ASYD_e-dbWbWXYg330E0occ/view?usp=sharing
    output: [data/landcover/*]

  # data bundle of the data folder for the poles
  bundle_landcover_northamerica:
    countries: [NorthAmerica]  # Greenland and antartica
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1018640/files/landcover_northamerica.zip?download=1
      gdrive: https://drive.google.com/file/d/1gu7PH08ZEpL4cBQa_fMUSq2m6LY1_UJo/view?usp=sharing
    output: [data/landcover/*]

  # data bundle of the data folder for the poles
  bundle_landcover_poles:
    countries: [GL, ATA]  # Greenland and antartica
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1018640/files/landcover_polar.zip?download=1
      gdrive: https://drive.google.com/file/d/1cUDcE6wpQVZNf3K9ffV6pNXfxq6sA65E/view?usp=sharing
    output: [data/landcover/*]

  # # data bundle of the data folder for the african continent
  # bundle_landcover_earth:
  #   countries: [Earth]
  #   category: landcover
  #   destination: "data/landcover"
  #   urls:
  #     direct: https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_WDOECM_Mar2022_Public_all_shp.zip
  #   output: [data/landcover/*]

  # # data bundle of the data folder for the african continent
  # bundle_landclassification:
  #   countries: [Earth]
  #   category: copernicus
  #   destination: "data/copernicus"
  #   urls:
  #     direct: https://zenodo.org/record/3939050/files/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif
  #   output: [data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif]

  # bundle_gebco:
  #   countries: [Earth]
  #   category: gebco
  #   destination: "data/gebco"
  #   urls:
  #     direct: https://www.bodc.ac.uk/data/open_download/gebco/gebco_2021/zip/
  #   unzip: True
  #   output: [data/gebco/GEBCO_2021_TID.nc]

  # bundle_eez:
  #   countries: [Earth]
  #   category: eez
  #   destination: "data/eez"
  #   urls:
  #     post:
  #       url: https://www.marineregions.org/download_file.php?name=World_EEZ_v11_20191118_gpkg.zip
  #       name: NAME
  #       organisation: ORGANISATION
  #       email: youremail@email.com
  #       country: Italy
  #       user_category: academia
  #       purpose_category: Research
  #       agree: 1
  #   output: [data/gebco/GEBCO_2021_TID.nc]

  # cutouts bundle of the cutouts folder for the african continent
  bundle_cutouts_africa:
    countries: [Africa]
    category: cutouts
    destination: "cutouts"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1016042/files/cutouts_africa.zip?download=1
      gdrive: https://drive.google.com/file/d/1-Njs7BqG0YE5QwBHj0zgkdicb5IQvQCh/view
    output: [cutouts/africa-2013-era5.nc]
    disable_by_opt:
      build_cutout: [all]
