# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

# File describing the data bundle configurations that can be downloaded
# by using the retrieve_databundle fule

# Each bundle shall have the following structure:

# .. code:: yaml

#   bundle_name:  # name of the bundle
#     countries: [country code, region code or country list]  # list of countries represented in the databundle
#     [tutorial: true/false]  # (optional, default false) whether the bundle is a tutorial or not
#     category: common/resources/data/cutouts  # category of data contained in the bundle:
#     destination: "."  # folder where to unzip the files with respect to the repository root (\"\" or \".\")
#     urls:  # list of urls by source, e.g. zenodo or google
#       zenodo: {zenodo url}  # key to download data from zenodo
#       gdrive: {google url}  # key to download data from google drive
#       protectedplanet: {url}  # key to download data from protected planet
#       direct: {url}  # key to download data directly from a url; if unzip option is enabled data are unzipped
#       post:  # key to download data using an url post request; if unzip option is enabled data are unzipped
#         url: {url}
#         [post arguments]
#     [unzip: true/false]  # (optional, default false) used in direct download technique to automatically unzip files
#     output: [...] # list of outputs of the bundle used in snakemake
#     [disable_by_opt:]  # option to disable outputs from the bundle; it contains a dictionary of options, each one with
#                        # each one with its output. When "all" is specified, the entire bundle is not executed
#       [{option}: [outputs]/all]  # list of options and the outputs to remove, or "all" corresponding to ignore everything

databundles:
  # tutorial bundle specific for Nigeria and Benin only
  bundle_tutorial_NGBJ:
    countries: [NG, BJ]
    tutorial: true
    category: data
    destination: "data"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/tutorial_data_NGBJ.zip?download=1
      gdrive: https://drive.google.com/file/d/1BSxmm3AG5TTOxrLG0ki8IdlL2n3hEviq/view
    output:
    - data/gebco/GEBCO_2021_TID.nc
    - data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif

  # tutorial bundle specific for Botswana only
  bundle_tutorial_BW:
    countries: [BW]
    tutorial: true
    category: data
    destination: "data"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/tutorial_data_BW.zip?download=1
      gdrive: https://drive.google.com/file/d/1aXqbCxEpe0aNI6EYuCLtFS6CbdXurTn7/view
    output:
    - data/gebco/GEBCO_2021_TID.nc
    - data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif

  # tutorial bundle specific for Morocco only
  bundle_tutorial_MA:
    countries: [MA]
    tutorial: true
    category: data
    destination: "data"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/tutorial_data_MA.zip?download=1
      gdrive: https://drive.google.com/file/d/1zY3WnKqwBF0derS4ncRIPpdTdNn978xw/view
    output:
    - data/gebco/GEBCO_2021_TID.nc
    - data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif

  # tutorial bundle specific for Nigeria and Benin only
  bundle_cutouts_tutorial_NGBJ:
    countries: [NG, BJ]
    tutorial: true
    category: cutouts
    destination: "cutouts"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/cutouts_NGBJ.zip?download=1
      gdrive: https://drive.google.com/file/d/1N6wJb-dBTqWZX1Tlf5y979lEPtqcVEfQ/view
    output: [cutouts/africa-2013-era5-tutorial.nc]
    disable_by_opt:
      build_cutout: [all]

  # tutorial bundle specific for Botswana only
  bundle_cutouts_tutorial_BW:
    countries: [BW]
    tutorial: true
    category: cutouts
    destination: "cutouts"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/cutouts_BW.zip?download=1
      gdrive: https://drive.google.com/file/d/1vtckYOZeSugDXrE0PGqxFwsVkdHNimhV/view
    output: [cutouts/africa-2013-era5-tutorial.nc]
    disable_by_opt:
      build_cutout: [all]

  # tutorial bundle specific for Morocco only
  bundle_cutouts_tutorial_MA:
    countries: [MA]
    tutorial: true
    category: cutouts
    destination: "cutouts"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/cutouts_MA.zip?download=1
      gdrive: https://drive.google.com/file/d/1ouIhGQ4e2M2FLzPUZgcKu5GSpRPZotqw/view
    output: [cutouts/africa-2013-era5-tutorial.nc]
    disable_by_opt:
      build_cutout: [all]

#tutorial bundle for all African countries
  bundle_tutorial_data_common:
    countries: [Africa]
    tutorial: true
    category: common
    destination: "data"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/tutorial_data_general.zip?download=1
      gdrive: https://drive.google.com/file/d/1nRLrs_kP0qVl-IHC4BFLjpoKa3HLk2Py/view
    output:
    - data/costs.csv
    - data/hydro_capacities.csv
    - data/custom_powerplants.csv
    - data/eez/eez_v11.gpkg
    - data/ssp2-2.6/2030/era5_2013/Africa.nc
    - data/ssp2-2.6/2030/era5_2013/Asia.nc
    - data/ssp2-2.6/2030/era5_2013/Europe.nc
    - data/ssp2-2.6/2030/era5_2013/NorthAmerica.nc
    - data/ssp2-2.6/2030/era5_2013/SouthAmerica.nc
    - data/ssp2-2.6/2030/era5_2013/Oceania.nc
    - data/hydrobasins/hybas_world_lev04_v1c.shp
    - data/hydrobasins/hybas_world_lev05_v1c.shp

  # data bundle containing the data of the data folder common to all regions of the world
  bundle_data_earth:
    countries: [Earth]
    category: common
    destination: "data"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/data_v0.1.zip?download=1
      gdrive: https://drive.google.com/file/d/1jN5iV_iaRa5lc1XOaEtletKPUgPNOVuf/view
    output:
    - data/costs.csv
    - data/hydro_capacities.csv
    - data/custom_powerplants.csv
    - data/eia_hydro_annual_generation.csv
    - data/eez/eez_v11.gpkg
    - data/gebco/GEBCO_2021_TID.nc
    - data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif
    - data/ssp2-2.6/2030/era5_2013/Africa.nc

  # resources bundle containing the resources folder for africa only
  bundle_natura_earth:
    countries: [Earth]
    category: natura
    destination: "data"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/natura_global.zip?download=1
      gdrive: https://drive.google.com/file/d/1WmAAwY0TAcHg8YZyAGof0bPewFacm7my/view
    output:
    - data/natura.tiff

  # data bundle of the data folder for the african continent
  bundle_landcover_africa:
    countries: [Africa]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/landcover_africa.zip?download=1
      gdrive: https://drive.google.com/file/d/1qnJ0HAWZ4z_9q3PtDEUrFmZWBZYg-WNW/view
    output: [data/landcover/*]

  # data bundle of the data folder for the african continent
  bundle_landcover_asiapacific:
    countries: [Asia, Oceania]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/landcover_asiapacific.zip?download=1
      gdrive: https://drive.google.com/file/d/163Uc9F1DPs2pRgDzkTivnblhXCw4nfd5/view
    output: [data/landcover/*]

  # data bundle of the data folder for the african continent
  bundle_landcover_latinamerica_caribbean:  # excludes north america
    countries: [SouthAmerica, NorthAmerica]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/landcover_latinamerica_caribbean.zip?download=1
      gdrive: https://drive.google.com/file/d/1d3l9qxPnM9XbXODWkP4kWxK_t5cDcEIZ/view
    output: [data/landcover/*]

  # data bundle of the data folder for the african continent
  bundle_landcover_westasia:
    countries: [WAS]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/landcover_westasia.zip?download=1
      gdrive: https://drive.google.com/file/d/1XsZVZDORUFMKyHfAkzqxDVBENiuy4jEM/view
    output: [data/landcover/*]

  # data bundle of the data folder for europe
  bundle_landcover_europe:
    countries: [Europe]
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/landcover_europe.zip?download=1
      gdrive: https://drive.google.com/file/d/1MfT3cwHJbNTtTjRLzW2T19f9qBNAxdhw/view
    output: [data/landcover/*]

  # data bundle of the data folder for the poles
  bundle_landcover_northamerica:
    countries: [NorthAmerica]  # Greenland and antartica
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/landcover_northamerica.zip?download=1
      gdrive: https://drive.google.com/file/d/1Dc11J2BZQQeJWxwCC6GiiPd_GWMCN0uF/view
    output: [data/landcover/*]

  # data bundle of the data folder for the poles
  bundle_landcover_poles:
    countries: [GL, ATA]  # Greenland and antartica
    category: landcover
    destination: "data/landcover"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/landcover_polar.zip?download=1
      gdrive: https://drive.google.com/file/d/18uODyONQZJGoL15P-URPl0lJs7sphQhX/view
    output: [data/landcover/*]

  # # data bundle of the data folder for the african continent
  # bundle_landcover_earth:
  #   countries: [Earth]
  #   category: landcover
  #   destination: "data/landcover"
  #   urls:
  #     direct: https://d1gam3xoknrgr2.cloudfront.net/current/WDPA_WDOECM_Mar2022_Public_all_shp.zip
  #   output: [data/landcover/*]

  # # data bundle of the data folder for the african continent
  # bundle_landclassification:
  #   countries: [Earth]
  #   category: copernicus
  #   destination: "data/copernicus"
  #   urls:
  #     direct: https://zenodo.org/record/3939050/files/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif
  #   output: [data/copernicus/PROBAV_LC100_global_v3.0.1_2019-nrt_Discrete-Classification-map_EPSG-4326.tif]

  # bundle_gebco:
  #   countries: [Earth]
  #   category: gebco
  #   destination: "data/gebco"
  #   urls:
  #     direct: https://www.bodc.ac.uk/data/open_download/gebco/gebco_2021/zip/
  #   unzip: True
  #   output: [data/gebco/GEBCO_2021_TID.nc]

  # bundle_eez:
  #   countries: [Earth]
  #   category: eez
  #   destination: "data/eez"
  #   urls:
  #     post:
  #       url: https://www.marineregions.org/download_file.php?name=World_EEZ_v11_20191118_gpkg.zip
  #       name: NAME
  #       organisation: ORGANISATION
  #       email: youremail@email.com
  #       country: Italy
  #       user_category: academia
  #       purpose_category: Research
  #       agree: 1
  #   output: [data/gebco/GEBCO_2021_TID.nc]

  # cutouts bundle of the cutouts folder for the african continent
  bundle_cutouts_africa:
    countries: [Africa]
    category: cutouts
    destination: "cutouts"
    urls:
      zenodo: https://sandbox.zenodo.org/record/1183583/files/cutouts_africa.zip?download=1
      gdrive: https://drive.google.com/file/d/1uCn7S5EHnPuaZHG5sWEVx2lT6Ve2r5dk/view
    output: [cutouts/africa-2013-era5.nc]
    disable_by_opt:
      build_cutout: [all]
