# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: SEA_ERA5_2013_IRENA_2050   # use this to keep track of runs with different settings
  base_config: config.SEA_base.yaml  # base configuration file
  shared_cutouts: true  # set to true to share the default cutout(s) across runs
                        # Note: value false requires build_cutout to be enabled

snapshots:
  start: '2013-01-01'
  end: '2014-01-01'
  inclusive: left   # end is not inclusive

scenario:
  opts: [Co2L0.050092-3H]

load_options:
  ssp: ssp2-2.6   # shared socio-economic pathway (GDP and population growth) scenario to consider
  weather_year: 2013  # Load scenarios available with different weather year (different renewable potentials)
  prediction_year: 2050  # Load scenarios available with different prediction year (GDP, population)
  scale: # scales all load time-series, i.e. 2 = doubles load
    BN: 2.204351157102163
    Java-Bali/ID: 3.0329325153988065
    KH: 5.144579516898982
    Kalimantan/ID: 0.21440216951811134
    LA: 4.031670201043937
    MM: 4.239266402689465
    Maluku/ID: 0.002414226926616292
    Nusa-Tenggara/ID: 0.056654846129243916
    PH: 3.681449819303459
    Papua/ID: 0.027206096020772015
    Peninsular/MY: 0.99508238781468
    SG: 1.2609364328437962
    Sabah/MY: 0.19873035798645336
    Sarawak/MY: 0.24428801361605457
    Sulawesi/ID: 0.15529619611874168
    Sumatra/ID: 0.8509975579342817
    TH: 1.9792969307730761
    VN: 5.509237403701934

atlite:
  nprocesses: 4
  cutouts:
    # geographical bounds automatically determined from countries input
    sea-2013-era5:
      module: era5
      dx: 0.3  # cutout resolution
      dy: 0.3  # cutout resolution

electricity:
  co2base: 1.008859e+09
  powerplants_filter: (DateOut >= 2050 or DateOut != DateOut)
  dateout_filter: 2040
  dateout_filter_renewable: 2050

renewable:
  onwind:
    cutout: sea-2013-era5
  offwind-ac:
    cutout: sea-2013-era5
  offwind-dc:
    cutout: sea-2013-era5
  solar:
    cutout: sea-2013-era5
  hydro:
    cutout: sea-2013-era5
  csp:
    cutout: sea-2013-era5

costs:
  year: 2050
