name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
    - envs/linux-pinned.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build Dev Container Image
      uses: devcontainers/ci@v0.3
      with:
        subFolder: .github
        cacheFrom: ghcr.io/${{ github.repository }}-dev-env
        imageName: ghcr.io/${{ github.repository }}-dev-env
        push: always
